language: python

matrix:
  include:
    - dist: trusty
      python: 3.6
      env: dist="14.04 LTS trusty"

    - dist: xenial
      python: 3.6
      env: dist="16.04 LTS xenial"
    - dist: xenial
      python: 3.7
      env: dist="16.04 LTS xenial"

    - dist: bionic
      python: 3.6
      env: dist="18.04 LTS bionic"
    - dist: bionic
      python: 3.7
      env: dist="18.04 LTS bionic"

install:
  - pip3 install -r testing_requirements.txt
  - pip3 install .

before_script:
  - psql --dbname=${TEST_DATABASE_URL} < tests/data.sql

script:
  - pytest -v --ignore=tests/test_services.py --ignore=tests/services/test_g_maps.py

notifications:
  email:
    on_success: never
