language: python

matrix:
  include:
    - dist: trusty
      python: 2.7
      env: dist="14.04 LTS trusty"
    - dist: trusty
      python: 3.7
      env: dist="14.04 LTS trusty"

    - dist: xenial
      python: 2.7
      env: dist="16.04 LTS xenial"
    - dist: xenial
      python: 3.7
      env: dist="16.04 LTS xenial"

    - dist: bionic
      python: 2.7
      env: dist="18.04 LTS bionic"
    - dist: bionic
      python: 3.7
      env: dist="18.04 LTS bionic"

install:
  - pip install .

script:
- python -m unittest discover -p 'test*.py' -v

notifications:
  email:
    on_success: never